import type { Metadata } from 'next';
import { Signika_Negative } from 'next/font/google';
import Head from 'next/head';
import './globals.css';
import { Providers } from './providers';
import Header from '@/components/header';

const nanum = Signika_Negative({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Uplift Buddy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nanum.className} bg-[#ffeebb]`}>
        <div className="">
          <Providers>
            <Header />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
